apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "agent-common.fullname" . }}
  labels:
    {{- include "agent-common.labels" . | nindent 4 }}
data:
  ONELINE_BACKTRACES: "true"
  RUST_BACKTRACE: {{ .Values.aetherium.rustBacktrace }}
  AET_DB: {{ .Values.aetherium.dbPath }}
  AET_LOG_FORMAT: {{ .Values.aetherium.tracing.format }}
  AET_LOG_LEVEL: {{ .Values.aetherium.tracing.level }}
  {{- range .Values.aetherium.chains }}
{{- include "agent-common.config-env-vars" (dict "config" . "key_name_prefix" (printf "chains_%s_" .name) "format" "config_map") | indent 2 }}
  {{- end }}
  AET_METRICSPORT: {{ .Values.aetherium.metrics.port | quote }}
