apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "agent-common.fullname" . }}-relayer-configmap
  labels:
    {{- include "agent-common.labels" . | nindent 4 }}
data:
  relayer-config.json: |
{{- toJson .Values.aetherium.relayer.configMapConfig | nindent 4 }}
