image:
  repository: gcr.io/abacus-labs-dev/aetherium-agent
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

# -- External Secret Store type and name
externalSecrets:
  # Available types: SecretStore, ClusterSecretStore
  storeType: ClusterSecretStore
  storeName:

podAnnotations: {}
podCommonLabels: {}

storage:
  storageClass: "standard"
  accessModes: ReadWriteOnce

# -- Aetherium Overrides
# By Default, Aetherium Agents load the config baked into the Docker Image
# Pass values here in order to override the values in the config
# Note: For successful operation, one _must_ pass signer keys as
#       they are not baked into the image for security reasons.
aetherium:
  # Defines what environment is being run
  runEnv: "default"
  context: "aetherium"
  # Set the DB location to be the volume
  dbPath: /usr/share/aetherium
  rustBacktrace: full
  tracing:
    # Set the log formatting
    format: json
    # Set the log level
    level: debug
  metrics:
    port: 9090
  aws: # true | false

  # -- Chain overrides, a sequence
  # This should mirror @aetherium-xyz/sdk AgentChainMetadata
  chains:
    - name: examplechain
      rpcConsensusType: fallback
      signer:
        type: # aws
      index:
        from:
        chunk:
        mode:
      mailbox:
      multisigIsm:
      interchainGasPaymaster:
      interchainSecurityModule:
      protocol: ethereum
      chainId:
      domainId:
      customRpcUrls:
        - example:
            url: https://example.com
            priority: 1
      blocks:
        confirmations:
        reorgPeriod:
        estimatedBlockTime:
      isTestnet: false

  # Aetherium Agent Roles
  # Individually Switchable via <role>.enabled
  validator:
    enabled: false
    podAnnotations:
      prometheus.io/port: "9090"
      prometheus.io/scrape: "true"
    podLabels: {}
    storage:
      size: 10Gi
      snapshot:
        enabled: false
        name: ""
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
    # -- How long to wait between checking for updates
    configs:
      []
      # - interval:
      #   checkpointSyncers:
      #   originChainName:
      #   type: # "hexKey"

  relayer:
    enabled: false
    aws: # true | false
    podAnnotations:
      prometheus.io/port: "9090"
      prometheus.io/scrape: "true"
    podLabels: {}
    storage:
      name: "state-premium"
      storageClass: "premium-immediate-rwo"
      size: 10Gi
      snapshot:
        enabled: false
        name: ""
    resources:
      requests:
        cpu: 1000m
        memory: 1024Mi
    envConfig:
      relayChains: ""
    configMapConfig: {}
    # -- Specify whether a default signer key is used for all chains in Values.aetherium.relayerChains list.
    # It affects chains whose signer type is hexKey.
    usingDefaultSignerKey: true

  relayerChains:
    - name: "alfajores"
      signer:
        type: # "aws"

  scraper:
    enabled: false
    podAnnotations:
      prometheus.io/port: "9090"
      prometheus.io/scrape: "true"
    podLabels: {}
    storage:
      size: 10Mi
      snapshot:
        enabled: false
        name: ""
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
    config:
      chainsToScrape: ""

  kathy:
    enabled: false

podSecurityContext:
  fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources:
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 250m
  #   memory: 1Gi

nodeSelector: {}

tolerations: []

affinity: {}
